return {
  cmd = {
    "node",
    vim.fn.expand "~/.local/share/manual-lsps/vscode-autohotkey2-lsp/server/dist/server.js",
    "--stdio",
  },
  filetypes = { "autohotkey", "autohotkey", "ah2" },
  workspace_required = false,
  flags = { debounce_text_changes = 500 },
  init_options = {
    locale = "en-us",
    InterpreterPath = vim.fn.exepath "autohotkey",
    AutoLibInclude = "All",
    CommentTags = "^;;\\s*(?<tag>.+)",
    CompleteFunctionParens = false,
    SymbolFoldinFromOpenBrace = false,
    Diagnostics = {
      ClassStaticMemberCheck = true,
      ParamsCheck = true,
    },
    ActionWhenV1IsDetected = "Continue",
    FormatOptions = {
      array_style = "expand",
      break_chained_methods = false,
      ignore_comment = false,
      indent_string = "\t",
      max_preserve_newlines = 2,
      brace_style = "One True Brace",
      object_style = "none",
      preserve_newlines = true,
      space_after_double_colon = true,
      space_before_conditional = true,
      space_in_empty_paren = false,
      space_in_other = true,
      space_in_paren = false,
      wrap_line_length = 0,
    },
  },
}
